/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppNavbar: typeof import('./src/components/AppNavbar.vue')['default']
    AudioPreferencesForm: typeof import('./src/components/preferences/AudioPreferencesForm.vue')['default']
    BehaviorPreferencesForm: typeof import('./src/components/preferences/BehaviorPreferencesForm.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    ButtonGroup: typeof import('./src/components/ButtonGroup.vue')['default']
    Card: typeof import('./src/components/card/Card.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    CopyButton: typeof import('./src/components/CopyButton.vue')['default']
    Dropzone: typeof import('./src/components/Dropzone.vue')['default']
    FormField: typeof import('./src/components/FormField.vue')['default']
    GraphicsPreferencesForm: typeof import('./src/components/preferences/GraphicsPreferencesForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImportOszCard: typeof import('./src/components/beatmap/ImportOszCard.vue')['default']
    MapsetCard: typeof import('./src/components/beatmap/MapsetCard.vue')['default']
    OperatorBox: typeof import('./src/components/operator/OperatorBox.vue')['default']
    PreferencesForm: typeof import('./src/components/preferences/PreferencesForm.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    QColor: typeof import('quasar')['QColor']
    QLinearProgress: typeof import('quasar')['QLinearProgress']
    QSlider: typeof import('quasar')['QSlider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('./src/components/Switch.vue')['default']
    TabList: typeof import('./src/components/tabList/TabList.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
    Vec2ParameterControl: typeof import('./src/components/operator/Vec2ParameterControl.vue')['default']
    ViewportPreferencesForm: typeof import('./src/components/preferences/ViewportPreferencesForm.vue')['default']
    VNodes: typeof import('./src/components/VNodes.vue')['default']
  }
}
