/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharedTextInput: typeof import('./src/components/SharedTextInput.vue')['default']
    ToolbarButton: typeof import('./src/components/ToolbarButton.vue')['default']
    VolumeSlider: typeof import('./src/components/VolumeSlider.vue')['default']
  }
}
