export {
  shallowRef as ref,
  ref as deepRef,
  shallowReactive as reactive,
  reactive as deepReactive,
  computed,
  getCurrentScope,
  EffectScope,
  effectScope,
  customRef,
  toRaw,
  isReactive,
  isRef,
  isReadonly,
  effect,
  onScopeDispose,
  onEffectCleanup,
  unref,
  getCurrentWatcher,
  toValue,
  watch,
  shallowReadArray,
} from "@vue/reactivity";
export type {
  WatchHandle,
  WatchSource,
  MaybeRefOrGetter,
  MaybeRef,
  BaseComputedRef,
  Builtin,
  ComputedGetter,
  ComputedRef, ComputedSetter,
  CustomRefFactory,
  DebuggerEvent,
  DebuggerEventExtraInfo,
  DebuggerOptions,
  DeepReadonly,
  Ref,
  Reactive,
  ReactiveEffect,
  ReactiveEffectOptions,
  WatchCallback,
  WatchEffect,
  WatchOptions,
  WatchScheduler,
} from "@vue/reactivity";

