export enum LegacyManiaSkinConfigurationLookups {
  ColumnWidth,
  ColumnSpacing,
  LightImage,
  LeftLineWidth,
  RightLineWidth,
  HitPosition,
  ComboPosition,
  ScorePosition,
  LightPosition,
  StagePaddingTop,
  StagePaddingBottom,
  HitTargetImage,
  ShowJudgementLine,
  KeyImage,
  KeyImageDown,
  NoteImage,
  HoldNoteHeadImage,
  HoldNoteTailImage,
  HoldNoteBodyImage,
  HoldNoteLightImage,
  HoldNoteLightScale,
  WidthForNoteHeightScale,
  ExplosionImage,
  ExplosionScale,
  ColumnLineColour,
  JudgementLineColour,
  ColumnBackgroundColor,
  ColumnLightColour,
  ComboBreakColour,
  MinimumColumnWidth,
  LeftStageImage,
  RightStageImage,
  BottomStageImage,

  // ReSharper disable once InconsistentNaming
  Hit300g,

  Hit300,
  Hit200,
  Hit100,
  Hit50,
  Hit0,
  KeysUnderNotes,
  NoteBodyStyle,
  LightFramePerSecond,
}
