// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {ClientCommand} from "./ClientCommand";

export interface ClientToServerMessage {
  responseId: string | null;
  command: ClientCommand;
}
