// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {IVec2} from "./IVec2";
import type {SliderControlPoint} from "./SliderControlPoint";

export interface HitObjectOverrides {
  time: number | null;
  position: IVec2 | null;
  newCombo: boolean | null;
  controlPoints: Array<SliderControlPoint> | null;
  expectedDistance: number | null;
  repeatCount: number | null;
}
