// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {HitObjectKind} from "./HitObjectKind";
import type {IVec2} from "./IVec2";

export interface HitObject {
  id: number;
  selectedBy: number | null;
  startTime: number;
  position: IVec2;
  newCombo: boolean;
  data: HitObjectKind;
}
