// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {SliderControlPoint} from "./SliderControlPoint";

export type HitObjectKind = { type: "circle" } | {
  type: "slider";
  expectedDistance: number;
  controlPoints: Array<SliderControlPoint>;
  repeats: number;
} | { type: "circle" } & null;
