// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {HitObject} from "./HitObject";
import type {HitObjectOverrides} from "./HitObjectOverrides";
import type {ServerState} from "./ServerState";
import type {ServerTick} from "./ServerTick";
import type {ServerToClientMessage} from "./ServerToClientMessage";
import type {TimingPoint} from "./TimingPoint";
import type {UserInfo} from "./UserInfo";

export type ServerCommand =
  | { type: "multiple"; payload: Array<ServerToClientMessage> }
  | { type: "ownId"; payload: number }
  | { type: "userJoined"; payload: UserInfo }
  | { type: "userLeft"; payload: UserInfo }
  | { type: "tick"; payload: ServerTick }
  | { type: "userList"; payload: Array<UserInfo> }
  | { type: "hitObjectCreated"; payload: HitObject }
  | { type: "hitObjectUpdated"; payload: HitObject }
  | { type: "hitObjectDeleted"; payload: number }
  | {
    type: "hitObjectSelected";
    payload: { ids: Array<number>; selectedBy: number | null };
  }
  | { type: "state"; payload: ServerState }
  | { type: "timingPointCreated"; payload: TimingPoint }
  | { type: "timingPointUpdated"; payload: TimingPoint }
  | { type: "timingPointDeleted"; payload: number }
  | {
    type: "hitObjectOverridden";
    payload: { id: number; overrides: HitObjectOverrides };
  };
