// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {UserTick} from "./UserTick";

export interface ServerTick {
  userTicks: Array<UserTick>;
}
