// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Difficulty} from "./Difficulty";
import type {HitObject} from "./HitObject";
import type {TimingPoint} from "./TimingPoint";

export interface ServerState {
  difficulty: Difficulty;
  hitObjects: Array<HitObject>;
  timingPoints: Array<TimingPoint>;
}
