// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {IVec2} from "./IVec2";
import type {SliderControlPointKind} from "./SliderControlPointKind";

export interface SliderControlPoint {
  position: IVec2;
  kind: SliderControlPointKind;
}
