// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {TimingInformation} from "./TimingInformation";

export interface TimingPoint {
  id: number;
  offset: number;
  timing: TimingInformation | null;
  sv: number | null;
  volume: number | null;
}
