// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Vec2} from "./Vec2";

export interface UserTick {
  id: number;
  cursorPos: Vec2 | null;
  currentTime: number;
}
