deployment:
  port: 3001

session:
  secret: dummy-secret

oauth:
  clients:
    osu:
      clientId:
      clientSecret:
      callbackUrl: 'http://localhost:3001/auth/osu/callback'

  authorization:
    multiplayer:
      issuer: 'http://localhost:3001'
      audience: 'http://localhost:3000'
      secret:
