/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-pixi-assets. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'virtual:pixi-assets' {
  import type {
    AssetRecordInfo
  } from 'unplugin-pixi-assets/runtime'

  /**
   * Assets list generated by unplugin-pixi-assets. 
   */
  export interface AssetNamedMap {
    "icon:circle": AssetRecordInfo<"icon:circle", "/src/assets/icons/circle.png", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
    "icon:clap@2x": AssetRecordInfo<"icon:clap@2x", "/src/assets/icons/clap@2x.png", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
    "icon:cog": AssetRecordInfo<"icon:cog", "/src/assets/icons/cog.png", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
    "icon:cursor-sizeew": AssetRecordInfo<"icon:cursor-sizeew", "/src/assets/icons/cursor-sizeew.svg", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
    "icon:cursor": AssetRecordInfo<"icon:cursor", "/src/assets/icons/cursor.svg", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
    "icon:finish@2x": AssetRecordInfo<"icon:finish@2x", "/src/assets/icons/finish@2x.png", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
    "icon:minus": AssetRecordInfo<"icon:minus", "/src/assets/icons/minus.png", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
    "icon:new-combo": AssetRecordInfo<"icon:new-combo", "/src/assets/icons/new-combo.png", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
    "icon:pen": AssetRecordInfo<"icon:pen", "/src/assets/icons/pen.png", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
    "icon:plus": AssetRecordInfo<"icon:plus", "/src/assets/icons/plus.png", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
    "icon:redo": AssetRecordInfo<"icon:redo", "/src/assets/icons/redo.png", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
    "icon:reverse": AssetRecordInfo<"icon:reverse", "/src/assets/icons/reverse.png", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
    "icon:select": AssetRecordInfo<"icon:select", "/src/assets/icons/select.png", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
    "icon:size-ew": AssetRecordInfo<"icon:size-ew", "/src/assets/icons/size-ew.png", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
    "icon:size-ns": AssetRecordInfo<"icon:size-ns", "/src/assets/icons/size-ns.png", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
    "icon:slider": AssetRecordInfo<"icon:slider", "/src/assets/icons/slider.png", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
    "icon:spinner": AssetRecordInfo<"icon:spinner", "/src/assets/icons/spinner.png", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
    "icon:undo": AssetRecordInfo<"icon:undo", "/src/assets/icons/undo.png", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
    "icon:whistle@2x": AssetRecordInfo<"icon:whistle@2x", "/src/assets/icons/whistle@2x.png", import("pixi.js").Texture,  import("pixi.js").TextureSourceOptions>
  }
}
