export enum OsuSkinComponents {
  HitCircle,
  ApproachCircle,
  SliderHeadHitCircle,
  SliderTailHitCircle,
  SliderScorePoint,
  SliderFollowCircle,
  ReverseArrow,
  SliderBall,
  FollowPoint,
  SpinnerBody,
  Cursor,
  CursorTrail,
  HitCircleSelect,

  JudgementGreat,
  JudgementOk,
  JudgementMeh,
  JudgementMiss,
}
