name: Build
on:
  push:
    branches:
      - master
jobs:
  build-beatmap-viewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release


      - run: pnpm install
      - run: pnpm exec nx run resources:prebuild --verbose
      - run: pnpm exec nx run beatmap-viewer:build

      - name: Docker Client Meta
        id: meta-client
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/minetoblend/osucad-beatmap-viewer
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha,prefix=

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: ./packages/beatmap-viewer
          file: ./packages/beatmap-viewer/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta-client.outputs.tags }}
          labels: ${{ steps.meta-client.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
