name: CI

on:
  push:
    branches:
      - main
      - dev
      - multiplayer
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'multiplayer'

      - name: Test & Build
        run: pnpm exec nx affected -t lint test build
